### ISSUE TITLE
[EPIC] Datastore-query-builder app v0.0.1

### ISSUE THREAD

**Issue by anuveyatsu** [datopian/datastore-query-builder#1]
## Acceptance criteria

* [x] I can see filters for datastore based resources
  * [x] I can add filters using any of the columns and operators such as `=`, `>`, `<`, `<=`, `>=`
  * [x] it then updates the preview table so I can see the filtered data
  * [x] I can see total number of rows after filters are applied
* [x] I can download filtered data

## Tasks

* [x] load a dataset object and init App component for each view that is based on Datastore resource
* [x] Filter component for filters UI
  * [x] displays filters
  * [x] handles user input and updates a datastore resource path with applied filters
* [x] data fetcher
* [x] update preview data
* [x] downloadables

## Analysis

https://gitlab.com/datopian/eds/eds-pm/issues/94

**Comment by anuveyatsu** [comment]
The main PR for this epic - #3

**Comment by anuveyatsu** [comment]
FIXED, see example of usage in EDS staging site: https://frontend-v2-eds.herokuapp.com/tso-gas/gasflow

<img width="1051" alt="Screen Shot 2019-07-19 at 14 34 55" src="https://user-images.githubusercontent.com/17809581/61521603-6d478080-aa32-11e9-921e-387c42c243be.png">

**Comment by starsinmypockets** [comment]
@anuveyatsu Is this implemented by default in frontend v2?
